# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'traffic_light.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtWidgets, uic

class TrafficLight(QtWidgets.QMainWindow):
    def __init__(self):
        super().__init__()
        uic.loadUi("traffic_light.ui", self)

        # Инициализация элементов
        self.red_light = self.label_red
        self.yellow_light = self.label_yellow
        self.green_light = self.label_green


        self.reset_lights()

        self.pushButton.clicked.connect(self.change_light)
        self.current_light = 0

    def reset_lights(self):
        self.red_light.setStyleSheet("background-color: gray; border-radius: 50px;")
        self.yellow_light.setStyleSheet("background-color: gray; border-radius: 50px;")
        self.green_light.setStyleSheet("background-color: gray; border-radius: 50px;")

    def change_light(self):
        self.reset_lights()


        if self.current_light == 0:
            self.red_light.setStyleSheet("background-color: red; border-radius: 50px;")
        elif self.current_light == 1:
            self.yellow_light.setStyleSheet("background-color: yellow; border-radius: 50px;")
        elif self.current_light == 2:
            self.green_light.setStyleSheet("background-color: green; border-radius: 50px;")


        self.current_light = (self.current_light + 1) % 3


if __name__ == "__main__":
    app = QtWidgets.QApplication([])
    window = TrafficLight()
    window.show()
    app.exec_()